name: CI Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test_chrono_intervals:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update local Rust toolchain
        run: |
          rustup update
          rustup install nightly
          rustup component add clippy rustfmt --toolchain nightly

      - name: Get toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version

      - name: Lint
        run: |
          cargo +nightly fmt -- --check
          cargo +nightly clippy -- -D warnings

      - name: Test
        run: |
          cargo check
          cargo test --all

      - name: Build
        run: |
          cargo build --release
